#!groovy


pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd mysterious-fail-1/ && docker build . --build-arg USERID=$(id -u jenkins) -t reversing-figlet'
            }
        }
        stage('Test') {
            steps {
                sh '''
                set -ex
                cd mysterious-fail-1
                docker build . -f Dockerfile.test --build-arg USERID=$(id -u jenkins) -t reversing-figlet-test

                docker run --rm -i -v "$(pwd)/build/:/app/build" reversing-figlet-test pytest --junitxml=build/junit.xml
                '''
                junit 'mysterious-fail-1/build/junit.xml'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
